# CHAPTER 80: Shoreline {-}
REVIEW OF PROJECTS IN THE SHOREZONE AND LAKEZONE

## <b> 80.1 </b> PURPOSE {-}

  The Shorezone Subelement, Conservation Element of the Goals and Policies identifies special qualities, including      physical, biological and visual, that shall be considered when reviewing a project in the shorezone or lakezone.  In   accordance with those policies, this chapter sets forth findings that must be made by TRPA prior to approving a       project in the shorezone or lakezone.

## <b> 80.2 APPLICABILITY </b> {-}

All projects and activities in lagoons or the shorezone or lakezone of any lake in the Region shall comply with the provisions of this chapter.

## <b> 80.3 REQUIRED FINDINGS </b> {-}

### <b> 80.3.1 Findings Required for Lakezone, Shorezone, and Lagoon Projects. </b> {-}
No project or activity within the lakezone, shorezone, or lagoon of lakes in the Region, shall be approved unless TRPA makes all the applicable findings listed below.

### <b> 80.3.2 Findings for All Projects.</b> {-}

#### <b> A. General Environmental Findings. </b> {-}
TRPA must analyze and make the required environmental findings pursuant to Chapter 3, Environmental Documentation. In addition, such environmental findings must demonstrate that the project will not adversely impact:

1. Littoral processes;
2. Fish spawning;
3. Backshore stability; or
4. On-shore wildlife habitat, including wildfowl nesting areas. 

#### <b> B. Accessory Facilities. </b> {-}
TRPA must find that there are sufficient accessory facilities to accommodate the project. 

#### <b> C. Compatibility. </b> {-}
TRPA must find that the project is compatible with existing shorezone and lakezone uses or structures on, or in the immediate vicinity of, the littoral parcel; or that modifications of such existing uses or structures will be undertaken to assure compatibility.

#### <b> D. Water Dependent Use. </b> {-}
TRPA must find that the proposed use in the lakezone, nearshore, foreshore, or lagoon is water-dependent.







